In [1]:
# Create a null vector of size 10 but with the fifth value 1

import numpy as np

a = np.zeros(10)

In [2]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
a[5] = 1

In [4]:
print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [5]:
# Create a vector with values ranging from 10 to 49

b = np.arange(10,49)

In [6]:
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [7]:
# Create 3*3 matrix with values ranging from 0 to 8

c = np.arange(0,9)

In [8]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
c.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# Find the indices of non-zeros element in the matrix [1,2,0,0,4,0]

d = np.array([1,2,0,0,4,0])

In [12]:
l = []
for i in range(len(d)):
    if d[i] != 0:
        l.append(i)
print("The indices of the matrix at which elements are non-zero are ",l)

The indices of the matrix at which elements are non-zero are  [0, 1, 4]


In [15]:
# Create a 10x10 array with random values and find the minimum and maximum values.

import random

arr = np.random.randint(1,10,100)

In [16]:
arr

array([6, 4, 9, 9, 2, 9, 1, 3, 1, 9, 9, 4, 1, 9, 9, 9, 7, 3, 2, 2, 6, 5,
       6, 8, 6, 8, 6, 3, 9, 5, 9, 2, 1, 5, 7, 7, 6, 3, 6, 4, 1, 8, 6, 1,
       1, 6, 7, 5, 5, 5, 2, 4, 6, 4, 9, 3, 1, 8, 1, 5, 7, 1, 9, 1, 6, 2,
       1, 6, 2, 2, 7, 7, 7, 2, 6, 1, 7, 8, 7, 5, 9, 8, 6, 8, 8, 2, 1, 6,
       6, 8, 2, 9, 8, 1, 2, 2, 7, 5, 6, 8])

In [17]:
arr.reshape(10,10)

array([[6, 4, 9, 9, 2, 9, 1, 3, 1, 9],
       [9, 4, 1, 9, 9, 9, 7, 3, 2, 2],
       [6, 5, 6, 8, 6, 8, 6, 3, 9, 5],
       [9, 2, 1, 5, 7, 7, 6, 3, 6, 4],
       [1, 8, 6, 1, 1, 6, 7, 5, 5, 5],
       [2, 4, 6, 4, 9, 3, 1, 8, 1, 5],
       [7, 1, 9, 1, 6, 2, 1, 6, 2, 2],
       [7, 7, 7, 2, 6, 1, 7, 8, 7, 5],
       [9, 8, 6, 8, 8, 2, 1, 6, 6, 8],
       [2, 9, 8, 1, 2, 2, 7, 5, 6, 8]])

In [18]:
arr.min()

1

In [19]:
arr.max()

9

In [20]:
# Create a random vector of size 30 and find the mean value.

arr_vec = np.arange(1,30,1)

In [21]:
arr_vec

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
arr_vec.mean()

15.0